### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by al00014** [ihmeuw/dismod_mr#22]
Hi AB,
I have been show watching closely at this site for the past few months. Glad that you've been updated the scripts to match with py3. However, I still find the installation process quite complicated. Are the dismod-mr only compatible with 32bit py3 on both mac os and windows now?
Or do your teams at IHME actually run everything on linux instead?

Thank you for your time in reading the message.

Yours sincerely,
Antonio

**Comment by aflaxman** [comment]
I have had reports of success using this on mac and windows, but I have only used it on linux.  I hope (the install notes that Ver created)[https://github.com/ihmeuw/dismod_mr#installation] are helpful, and if you have additions or clarifications, your patches are most definitely welcome!

**Comment by sKusumpa** [comment]
Hi Dr.  Flaxman, following up on this thread.  

My name is Don and  I'm a student at Benedictine University focusing on Public Health Epidemiology.  It is very nice to meet you. 

Ver's installation notes are helpful, however since there are updates to the dismod_mr files (as recent as last year) her notes may be outdated. It may be difficult to replicate her environment considering the year her notes were written (thinking it was in 2013, as that is the latest year stated in the development timeline in the "Introduction" paragraph).  Even if successfully replicating Ver's environment (platform, computer, OS, packages, and time) we'd still need the dismod_mr installation files she used at that time in successful progress her installation process.

Despite that, I've successfully installed dismod_mr on my MacBookPro 2017 10.14.3.  Yet, I have some errors when running the Parkinson's disease motivating example.  Would be great to get your feedback, perhaps on another thread?  I'm not a programmer by trade, but I think it will be a productive conversation that might be useful for dismod_mr.

On another note, thank you for mentioning that dismod_mr is best utilized on Linux, do you have installation notes for Linux?

Thank you and have a great day. 
Best, Don

**Comment by aflaxman** [comment]
Dear Don,

Thanks for your interest in this work.

There are not currently installation notes for Linux.  Patches welcome!

If you share a description of what you did with the Parkinson's example and what went wrong, I'll see if I can help you get it sorted out.

--Abie

**Comment by sKusumpa** [comment]
Thank you so much Dr. Flaxman for your response.  Which version of Linux does your team use for Dismod?  That would be great to know as I'm comfortable with 17.04 Ubuntu but willing to try other flavors/versions.  I'm going to try that in addition to troubleshooting my current Mac installation of Dismod and working through the Parkinson's example

Below is the description of what I did with the Parkinson's example.  Thank you again and look forward to your guidance.  Best, Don

Installation:
MacBookPro 2017, Mojave 10.14.13
Python (2.7.15)
iPython (5.8)
Jupyter (4.4.)

Packages(versions):
pymc (2.3.6)
scipy (1.1.0)
matplotlib (2.2.3)
pandas (0.23.4)
networkx (2.2)

After installation, I began to run the Parkinson's example.  My terminal defaults my iPython to Jupyter (iPython subcommand deprecated).  I get some results when running through the cells in the notebook.  I am able to produce some output despite errors (individually running the cells).   Here is a breakdown of the errors:

**AttributeError: 'Series' object has no attribute 'sort'**  I believe this occurs when trying to read pandas, the __getattribute__ function.  Screenshots below

<img width="927" alt="Screen Shot 2019-04-04 at 09 06 15" src="https://user-images.githubusercontent.com/49060698/55537575-d04c1c00-56bc-11e9-9797-ff3b3d731eeb.png">

<img width="933" alt="Screen Shot 2019-04-04 at 09 06 24" src="https://user-images.githubusercontent.com/49060698/55537584-d6da9380-56bc-11e9-91df-10d6f3a5cc73.png">

**KeyError: 'p'** I believe this is also related to pandas, but also may be global (as a dismod function calls for "p".  When calling the __name__ function for some reason it doesn't recognize 'p'.  Screenshots below.

<img width="726" alt="Screen Shot 2019-04-04 at 09 07 38" src="https://user-images.githubusercontent.com/49060698/55538031-c4ad2500-56bd-11e9-98c0-24224fd688a8.png">

<img width="809" alt="Screen Shot 2019-04-04 at 09 07 31" src="https://user-images.githubusercontent.com/49060698/55538095-ec9c8880-56bd-11e9-9da6-c0d497753853.png">

**ValueError: The name argument must be a string, but received alpha_p_ISR** . Not sure what is happening here, most likely a result of the previous errors not being addressed.  Screenshot below.

<img width="501" alt="Screen Shot 2019-04-04 at 09 07 15" src="https://user-images.githubusercontent.com/49060698/55538267-59178780-56be-11e9-8642-7c65996a84ff.png">

**Comment by aflaxman** [comment]
Sorry this has taken me so long to respond to. I really need to update things here, this notebook has gotten way out-of-date with modern Python and Pandas.  Here is a quick fix the the `_round` cell that broke first:
```
import numpy as np
np.round(summary,3).sort_values('count', ascending=False)
```

I don't have time to work out more now, but I'll keep this on my to-do list, and apologize again for it being so broken.

**Comment by sKusumpa** [comment]
Thank you Dr. Flaxman for this.  I'll implement it and share with you the results. 

As an update I went through some Python tutorials (Code Academy) and have a better sense of the code now (I think).  I believe I see how the  _round cell broke because it didn't have the "np" in the "np.round" command.  Let me know if I'm on the right track and I can try to look at other issues that I come upon in the same manner.

Thank you so much.
Have a great one. 
Best, Don

**Comment by sKusumpa** [comment]
Hi Dr. Flaxman a quick update.  The new code worked, here's the screenshot.  I'll try to troubleshoot through the other cells but if you have further guidance that would be great to hear.  

Also I'm still thinking about installing Linux on my Mac's Virtual Box so if you have suggestions on which flavor and version Dismod works the best on that would be great (I already have a 17.04 on my Virtual Box).

Here's the screenshot:
<img width="1101" alt="Screen Shot 2019-05-16 at 17 49 53" src="https://user-images.githubusercontent.com/49060698/57892173-a29ddb00-7803-11e9-957c-6e2073116ece.png">

Thanks Dr. Flaxman.

**Comment by aflaxman** [comment]
I've just pushed out some work-in-progress on this, that you might find useful.  See here: https://github.com/ihmeuw/dismod_mr/pull/25

This uses Numba instead of pycppad, which I find easier to install, and also updates several notebooks to work with more modern scientific python conventions. It is still work-in-progress, though, and I need to fix a few more issues before I can merge it into the main code.

**Comment by sKusumpa** [comment]
Thanks Dr. Flaxman, I'll try your work in progress implementing Numba instead of pycppad.  I think that will increase the likelihood for it to work on my machine, as pycppad has some issues for me (and some of my colleagues that I asked).  I'd like to remove just pycppad and install Numba without reinstalling my entire environment.  If that's what you did let me know, otherwise I'll keep you updated on my progress.  Thank you so much. Best, Don

**Comment by aflaxman** [comment]
Good luck!  Let me know if you still have trouble.

**Comment by sKusumpa** [comment]
Thanks Dr. Flaxman, one quick question.  Should I use Anaconda 2 or 3? Or would that matter?

Thank you.  Best, Don

**Comment by sKusumpa** [comment]
Hi Dr. Flaxman, I was able to install the Anaconda Dismod environment (very nice), and pymc is installed correctly (checked via pymc --version).  However when I begin to run through the Parkinson's example in Jupyter it says it can't find pymc, but finds all the other packages.  I looked into the $PATH while in the Dismod environment and it shares this as the first path:

/anaconda2/envs/dismod_mr/bin

I looked in that folder and PYMC wasn't in there.  I also noticed that when I activate the Dismod environment it overwrites my initial first $PATH of 

/anaconda2/bin

with the  "/anaconda2/envs/dismod_mr/bin"

So is there a specific $PATH I should point to within the Anaconda Dismod environment for PYMC? Say add /anaconda2/pkgs or /anaconda2/bin (or simliar)? 

I have other paths on my $PATH, these include (by hierarchy):

/anaconda2/condabin:
/Library/Frameworks/Python.framework/Versions/3.7/bin:
/usr/bin:/bin:/usr/sbin:
/sbin:
/usr/local/gfortran
/usr/local/bin
/Users/home/Library/Python/2.7/bin
/Users/home/Library/Python/2.7
/Users/home/Library/Python
/Library/Developer
/Applications/CMake.app/Contents/bin
/Users/home/Desktop
/anaconda2/cmake-bin/bin

So let me know what you think and thank you.  Have a great one.  Best, Don

**Comment by aflaxman** [comment]
It sounds like maybe your `conda install pymc` did not happen in your `dismod_mr` virtual environment.  My environments get very confused this way sometimes!  Try `conda install --yes pymc` from your jupyter notebook, and/or make sure that your jupyter notebook is using your `dismod_mr` environment (I made [notes on how I got that to work a while ago](https://healthyalgorithms.com/2018/10/18/jupyter-notebooks-for-conda-environments-for-python/).)

**Comment by sKusumpa** [comment]
Thanks Dr. Flaxman for the insight. I will try that piece of code in Jupyter and let you know.  Much appreciated.  Best, Don
